spring.application.name=smart-network-managment
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SmartNetworkManagement;encrypt=true;trustServerCertificate=true
spring.datasource.username=user
spring.datasource.password=user1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true